### PR TITLE
Incredibly lazy go.mod conversion

### PR DESCRIPTION
**Pull request by arodland**
This could probably be done better, but I want to be able to reference it in an issue.

### CODE REVIEW

**Comment by nskalis** [comment]
this works! please merge to master. it is a definite improvement over the current status / glide

**Comment by junr03** [comment]
@arodland thanks for doing this. Do you mind making this work with CI

current error:
```
$ make bootstrap
go get
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
can't load package: package github.com/lyft/ratelimit: no Go files in /home/travis/gopath/src/github.com/lyft/ratelimit
```

**Comment by junr03** [comment]
@rodaine do you mind taking a look, and advising on migrating to go modules?

**Comment by arodland** [comment]
@junr03 sorry, I'm not that familiar with Travis, and trying to research the situation with Go modules and Travis leads to a lot of confusion. If someone makes a suggestion I will implement it.

**Comment by danielhochman** [comment]
See https://dave.cheney.net/2018/07/16/using-go-modules-with-travis-ci.

You need to add `env GO111MODULE=on` in `.travis.yml` or otherwise set the environment variable in the `Makefile`.

We're also going to need to update the `Dockerfile` since it still references `glide`.

**Comment by nskalis** [comment]
giving this a little push.. since I am in such a need this to land on the official repository and thanks @arodland it was made possible.

following @danielhochman advice about travis, @arodland is it sth that you can push forward ?

**Comment by rodaine** [comment]
> @rodaine do you mind taking a look, and advising on migrating to go modules?

This looks fine to me, pending fixing CI. Services are probably the most safe to upgrade, while libraries, especially those >= v2 will have impact on dependents that haven't migrated to modules yet (due to the import path breaking behavioral changes).

**Pull request closed without merging**
