### PR TITLE
Ambassador doc

### PR DESCRIPTION
**Pull request by Abhishek627**
Deleting dockerfile as we discussed and updating the documentation with ambassador use case.

### CODE REVIEW

**Comment by sidmalik123** [comment]
Hi @Abhishek627 , I just wanted to know the reason for removing the docker file

**Comment by Abhishek627** [comment]
Hi @sidmalik123 ! Please see the reasoning here : https://github.com/lyft/ratelimit/pull/84

**Comment by sidmalik123** [comment]
@Abhishek627 @junr03 I feel like the docker file is useful for people who want to use the project in kubernetes.

**Comment by stevesloka** [comment]
I'm the one who added the `Dockerfile` initially, I wanted it because we're building an image since one doesn't exist today. Related to #57

**Comment by Abhishek627** [comment]
@sidmalik123 @stevesloka I used the same Dockerfile for my project too. For k8, I think kompose can be used to create kubernetes resource file from the docker-compose file. But I agree, If many people are using the Dockerfile, we should leave that in.

**Comment by junr03** [comment]
@Abhishek627 lets keep this PR only to the ambassador blog post. We can discuss the Dockerfile issue elsewhere.

**Pull request closed without merging**
